### ISSUE TITLE
Re-Engineer Code Refactoring

### ISSUE THREAD

**Issue by pepcus-pratik** [Pepcus/yjsgUI#212]
Subtask of #211 

Tasks:
- [x] Remove cssVariables.json https://github.com/Pepcus/yjsgUI/issues/213
- [x] Improve config directory structure
- [x] Modify Route component to consume configuration https://github.com/Pepcus/yjsgUI/issues/214
- [x] Refactor Reducers
- [x] Separate out sagas and apis https://github.com/Pepcus/yjsgUI/issues/215
- [x] Separate out form validation functions and add support for tenant specific validations
- [x] Create apis utils directory in utils https://github.com/Pepcus/yjsgUI/issues/216
- [x] Create common utils directory in utils https://github.com/Pepcus/yjsgUI/issues/217
- [x] Refactor actions and have separate actions for each root reducer
- [x] Refactor apis directory https://github.com/Pepcus/yjsgUI/issues/230
- [x] Modify application bootstrap mechanism https://github.com/Pepcus/yjsgUI/issues/231
- [x] Refactor sagas directory https://github.com/Pepcus/yjsgUI/issues/243
- [x] Make application constants configurable https://github.com/Pepcus/yjsgUI/issues/243
- [x] Modify theme management functionality https://github.com/Pepcus/yjsgUI/issues/246
- [x] Make API endpoints and response/request formatter configurable via JSON https://github.com/Pepcus/yjsgUI/issues/184
- [x] Cleanup constant files
- [x] Remove dependency of appConfig.json https://github.com/Pepcus/yjsgUI/issues/254
- [x] Move form configurations on the route specific JSON https://github.com/Pepcus/yjsgUI/issues/255
