### ISSUE TITLE
Separate out sagas and apis

### ISSUE THREAD

**Issue by pepcus-pratik** [Pepcus/yjsgUI#215]
**TODOs:**
- [ ] create directories **sagas** and **apis** under src/
- [ ] move all **sagas** into the sagas directory
- [ ] move all **apis** into the apis directory
