### ISSUE TITLE
Create apis utils directory in utils

### ISSUE THREAD

**Issue by pepcus-pratik** [Pepcus/yjsgUI#216]
**TODOs:**
- [ ] create **apis** directory in utils
- [ ] create util file for different apis under apis/ directory.
- [ ] export all of them from a common index
