### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by pepcus-pratik** [Pepcus/yjsgUI#266]
### Scope:
To cover the necessary documentation for the new EMS application.

**Tasks:**
- [ ] Steps to register new tenant #259
- [ ] Guide for the configurable APIs
- [ ] Guide to use the generic API caller
- [ ] Document significance of different JSON files
- [ ] Guide to prepare application's theme
